"""Context auto-compaction for long agent sessions.

When a prompt approaches the model's context window, we reduce it in two stages:

1. **Heuristic truncation** (cheap, no LLM call): replace large role=tool
   contents with short placeholders. Agent sessions accumulate large file
   reads from `read` / `bash` tool calls whose full content is usually only
   needed for the turn they were returned; once we've moved past those turns
   the content is dead weight.

2. **LLM summarization** (falls back to if stage 1 isn't enough): collapse
   the "middle" of the conversation into a single synthetic user message
   containing a concise summary generated by the current engine.

Both stages preserve the **atomic-group invariant**: an assistant message
that emitted tool_calls is never separated from the role=tool response(s)
that answer those calls. Splitting a group breaks Qwen's chat template
(it iterates tool_call_ids) and leaves Kilo with orphan tool results.

The caller holds the GPU lock if stage 2 fires — summarization calls
`engine.generate()` which must be serialized with the main request's
forthcoming generate call.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class CompactStats:
    triggered: bool = False
    stage: str = "none"       # "none" | "truncation" | "summary"
    before_tokens: int = 0
    after_tokens: int = 0
    tool_results_truncated: int = 0
    messages_summarized: int = 0

    @property
    def tokens_saved(self) -> int:
        return max(0, self.before_tokens - self.after_tokens)

    def as_dict(self) -> dict:
        return {
            "triggered": self.triggered,
            "stage": self.stage,
            "before_tokens": self.before_tokens,
            "after_tokens": self.after_tokens,
            "tokens_saved": self.tokens_saved,
            "tool_results_truncated": self.tool_results_truncated,
            "messages_summarized": self.messages_summarized,
        }


@dataclass
class _Group:
    """An atomic message group that must be kept or dropped as a unit."""
    messages: list[dict] = field(default_factory=list)


def _atomic_groups(messages: list[dict]) -> list[_Group]:
    """Split messages into atomic groups.

    Groups:
    - Leading system message(s) → one group each.
    - Any user/assistant-without-tool_calls message → one group each.
    - assistant-with-tool_calls + all contiguous role=tool messages → one group.
    """
    groups: list[_Group] = []
    i = 0
    n = len(messages)
    while i < n:
        msg = messages[i]
        if msg.get("role") == "assistant" and msg.get("tool_calls"):
            g = _Group(messages=[msg])
            j = i + 1
            while j < n and messages[j].get("role") == "tool":
                g.messages.append(messages[j])
                j += 1
            groups.append(g)
            i = j
        else:
            groups.append(_Group(messages=[msg]))
            i += 1
    return groups


def _tool_placeholder(msg: dict) -> dict:
    """Build a truncated placeholder for a role=tool message."""
    content = msg.get("content") or ""
    orig_len = len(content)
    call_id = msg.get("tool_call_id") or "unknown"
    name = msg.get("name") or "?"
    placeholder = (
        f"[compacted: tool={name} call_id={call_id}, "
        f"original output was {orig_len} chars — elided to save context]"
    )
    out = dict(msg)
    out["content"] = placeholder
    return out


def _run_truncation(
    messages: list[dict],
    protected_tail: int,
    min_tool_content: int,
) -> tuple[list[dict], int]:
    """Replace large role=tool contents with placeholders, oldest-first.

    Returns (new_messages, count_truncated). The protected tail
    (last `protected_tail` atomic groups) is kept verbatim.
    """
    groups = _atomic_groups(messages)
    if len(groups) <= protected_tail:
        return messages, 0
    head = groups[:-protected_tail]
    tail = groups[-protected_tail:]
    truncated_count = 0
    new_head: list[_Group] = []
    for g in head:
        new_msgs: list[dict] = []
        for m in g.messages:
            if (
                m.get("role") == "tool"
                and isinstance(m.get("content"), str)
                and len(m["content"]) > min_tool_content
            ):
                new_msgs.append(_tool_placeholder(m))
                truncated_count += 1
            else:
                new_msgs.append(m)
        new_head.append(_Group(messages=new_msgs))
    flat: list[dict] = []
    for g in new_head + tail:
        flat.extend(g.messages)
    return flat, truncated_count


_SUMMARY_SYSTEM_PROMPT = (
    "You are a conversation summarizer. Produce a concise plain-text summary "
    "(max 300 words) of the prior agent conversation. Preserve: "
    "(1) what files/commands were read or executed, "
    "(2) key facts discovered about the codebase, "
    "(3) decisions made, "
    "(4) any open questions. "
    "Do not invent information. Output ONLY the summary — no preamble, "
    "no markdown code fences, no tool calls."
)


def _run_summarization(
    messages: list[dict],
    engine,
    protected_tail: int,
    gpu_lock,
) -> tuple[list[dict], int]:
    """Collapse middle groups into one synthetic user message with a summary.

    Protects the first system message and the last `protected_tail` groups.
    Returns (new_messages, count_groups_summarized).
    """
    groups = _atomic_groups(messages)
    # Protected head = first group if it's a system message; else empty.
    head_count = 1 if groups and groups[0].messages[0].get("role") == "system" else 0
    if len(groups) - head_count <= protected_tail:
        return messages, 0

    head = groups[:head_count]
    middle = groups[head_count:-protected_tail]
    tail = groups[-protected_tail:]

    if not middle:
        return messages, 0

    # Render the middle as a plain conversation transcript for the summarizer.
    transcript_parts: list[str] = []
    for g in middle:
        for m in g.messages:
            role = m.get("role", "user")
            content = m.get("content") or ""
            if m.get("tool_calls"):
                # Render tool_calls as a brief listing so the summarizer knows
                # what was called.
                calls = "; ".join(
                    f"{c.get('function', {}).get('name', '?')}("
                    f"{c.get('function', {}).get('arguments', '')})"
                    for c in m.get("tool_calls") or []
                )
                transcript_parts.append(f"[{role}] tool_calls: {calls}")
            if isinstance(content, str) and content.strip():
                # Cap per-message content in the transcript to keep the
                # summarization prompt itself bounded.
                snippet = content if len(content) < 2000 else content[:2000] + "…"
                transcript_parts.append(f"[{role}] {snippet}")
    transcript = "\n\n".join(transcript_parts)

    summarize_msgs = [
        {"role": "system", "content": _SUMMARY_SYSTEM_PROMPT},
        {"role": "user", "content": transcript},
    ]

    def _do_summarize() -> str:
        text, _metrics = engine.generate(
            summarize_msgs, max_tokens=500, tools=None,
        )
        return (text or "").strip()

    if gpu_lock is not None:
        with gpu_lock:
            summary = _do_summarize()
    else:
        summary = _do_summarize()

    if not summary:
        # Fallback: use a deterministic placeholder rather than risk sending
        # an empty prompt that confuses the model.
        summary = (
            f"[prior conversation: {len(middle)} turns compacted — content not "
            f"summarized (summarizer returned empty)]"
        )

    synthetic = {
        "role": "user",
        "content": f"[Summary of prior conversation]\n{summary}",
    }

    out: list[dict] = []
    for g in head:
        out.extend(g.messages)
    out.append(synthetic)
    for g in tail:
        out.extend(g.messages)
    return out, len(middle)


def _count_tokens(engine, messages: list[dict], tools: list[dict] | None) -> int:
    """Render+tokenize the messages to get a prompt-token count.

    Falls back to a byte-length heuristic (chars/4) when Jinja chat-
    template rendering fails — this happens when a message's `content`
    is a multimodal list (text + image parts) or contains sequences
    the template can't render. Failing the whole request because the
    compactor couldn't pre-count tokens is worse than a rough estimate.
    """
    try:
        return len(engine._apply_chat_template(messages, tools=tools))
    except Exception as e:
        import json as _json
        total = 0
        for m in messages:
            c = m.get("content")
            if isinstance(c, str):
                total += len(c)
            elif isinstance(c, list):
                # OpenAI-style multimodal parts
                for part in c:
                    if isinstance(part, dict):
                        total += len(part.get("text") or "")
                        # image_url counts as ~1000 tokens — conservative
                        if part.get("type") == "image_url":
                            total += 4000
            else:
                try: total += len(_json.dumps(c))
                except Exception: total += 32
        # chars → tokens ~= 4:1 for English+code
        return max(1, total // 4)


def compact(
    messages: list[dict],
    engine,
    *,
    tools: list[dict] | None = None,
    threshold: float = 0.75,
    target: float = 0.50,
    protected_tail: int = 4,
    min_tool_content: int = 500,
    enable_summarization: bool = True,
    gpu_lock=None,
) -> tuple[list[dict], CompactStats]:
    """Compact `messages` if its rendered prompt exceeds `threshold * context_window`.

    Args:
      messages: OpenAI-format message list.
      engine: MioEngine — used for tokenization and (stage 2) generation.
      tools: optional OpenAI tools list (must be identical to what the
             request will use so the token count matches).
      threshold: trigger compaction when prompt tokens > threshold * context_window.
      target: stop compacting when prompt tokens <= target * context_window.
      protected_tail: keep the last N atomic groups verbatim (recent context).
      min_tool_content: role=tool messages with content >= this many chars are
                        candidates for truncation.
      enable_summarization: if False, skip stage 2 (heuristic-only mode).
      gpu_lock: optional lock to acquire during stage 2 engine.generate().

    Returns:
      (new_messages, stats). `stats.triggered=False` means no changes.
    """
    ctx_window = int(getattr(engine.tier_config, "context_window", 32_768))
    threshold_tokens = int(ctx_window * threshold)
    target_tokens = int(ctx_window * target)

    before = _count_tokens(engine, messages, tools)
    stats = CompactStats(before_tokens=before, after_tokens=before)
    if before <= threshold_tokens:
        return messages, stats

    # Stage 1 — tool-result truncation
    truncated, n_trunc = _run_truncation(messages, protected_tail, min_tool_content)
    after1 = _count_tokens(engine, truncated, tools)
    if n_trunc > 0 and after1 <= target_tokens:
        stats.triggered = True
        stats.stage = "truncation"
        stats.tool_results_truncated = n_trunc
        stats.after_tokens = after1
        return truncated, stats

    # Stage 2 — summarization (only if enabled and stage 1 wasn't enough)
    if enable_summarization:
        summarized, n_sum = _run_summarization(
            truncated, engine, protected_tail, gpu_lock,
        )
        after2 = _count_tokens(engine, summarized, tools)
        stats.triggered = True
        stats.stage = "summary"
        stats.tool_results_truncated = n_trunc
        stats.messages_summarized = n_sum
        stats.after_tokens = after2
        return summarized, stats

    # Heuristic-only mode: stage 1 is our best effort even if it didn't hit target.
    stats.triggered = n_trunc > 0
    stats.stage = "truncation" if n_trunc > 0 else "none"
    stats.tool_results_truncated = n_trunc
    stats.after_tokens = after1
    return truncated, stats
